package biz.aliustaoglu.jetpacknavigation;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import androidx.fragment.app.Fragment;
import androidx.navigation.NavDirections;
import androidx.navigation.Navigation;


/**
 * A simple {@link Fragment} subclass.
 */
public class ListFragment extends Fragment implements View.OnClickListener {

    public ListFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_list, container, false);
        Button btn = view.findViewById(R.id.btn);
        btn.setOnClickListener(this);
        return view;
    }

    @Override
    public void onClick(View v) {

        // This is generated by safe args plugin
        NavDirections action = ListFragmentDirections.actionListFragmentToDetailFragment();

        // If we didn't use safeargs below could have worked as well
        //NavDirections action = new ActionOnlyNavDirections(R.id.action_listFragment_to_detailFragment);

        // Now call the action
        Navigation.findNavController(v).navigate(action);
    }
}
